### ISSUE TITLE
Remove/Move max_size parameter from finish function

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-vmm/vm-fdt#4]
In the current implementation of the `FdtWriter`, the maximum size of the DTB is checked at the end. If the size of the DTB is larger than the specified `max_size` an error is returned, otherwise DTB is padded such that the total size is `max_size`.

Chatted with @danielverkamp and this is a leftover from when they were using the C-based libfdt in crosvm, and it does not make a lot of sense to keep it this way.

The options we currently have are:
1. removing this check altogether
2. move the initialization of `max_size` to the `new` function, and in `finish` just check that the size is less then `max_size` without padding the structure with zeroes (as this is not actually a requirement). 

Since the caller of the FDT interface is trusted, there is not a lot of sense to add runtime checks for each function that increases the DTB size (the DTB size is directly proportional to the number of function calls in the public interface) as this would introduce delays.

I am fine with either approach (1 or 2), but I was wondering if anyone else has some strong preferences here.

Pinging a few more people: @jiangliu @alexandruag @lauralt @slp @dianpopa

**Comment by danielverkamp** [comment]
I am in favor of option 1, since this will remove some unnecessary complexity from the AP. The original max_size design came from libfdt's API, which used it to pre-allocate a buffer, but I just used a dynamically growing Vec<u8> in the vm-fdt implementation, so the max size is no longer used to control allocation. I believe libfdt also builds the string table in place inside this buffer, which I chose not to do in this crate; it's built separately and appended at the end during finish(), so there is some extra copying, but it means we don't need a fixed amount of buffer or a function like libfdt's compact call, since the produced DTB is already compact (strings directly after nodes).

We could also keep max_size and move it to the constructor as in option 2 and use it to pre-allocate space with `Vec::with_capacity()`, but I don't think this is a major performance win (I assume Vec does something like double when it expands, so the number of reallocations only grows logarithmically).

**Comment by alexandruag** [comment]
Hi! An interesting question is whether we want to leverage something like a `max_size` value to ensure the size of the blob does not increase arbitrarily (i.e. we keep an eye on the current size as various elements are added, and return an error if we ever go beyond `max_size`). I guess this would be something like an option 3, since it looks like option 2 above only checks at the very end. However, if we don't particularly benefit from safeguards against arbitrary growth of the generated object, then option 1 sounds good.

**Comment by andreeaflorescu** [comment]
I would stick with option 1. I was discussing with @danielverkamp over email and introducing a size check for every function introduces an unneeded overhead as the caller of the functions is considered trusted.

@danielverkamp do you want to add a PR with the fix, or should I?

**Comment by danielverkamp** [comment]
I uploaded a PR, and I will make an equivalent change on the crosvm side to keep compatibility.
